import type { FlowDefinition } from '../types'

export type ScenarioMeta = {
  id: string
  title: string
  subtitle: string
  flow: FlowDefinition
}

function spine(
  steps: string[],
  stepDelayMs: number,
): NonNullable<FlowDefinition['simulation']> {
  return { stepDelayMs, sequence: steps }
}

/** Shared ENTRY / EXIT topology helpers — each scenario keeps explicit terminals */
const S = 'n_start'
const E = 'n_end'

export const SCENARIOS: ScenarioMeta[] = [
  {
    id: 'card-capture',
    title: 'Card capture',
    subtitle: 'Ingest → fraud diamond → approval → settlement + retry loop',
    flow: {
      id: 'card-capture',
      name: 'Card capture → fraud → approval → settlement',
      metadata: { domain: 'payments' },
      nodes: [
        { id: S, kind: 'start', label: 'Entry' },
        { id: 'npay', kind: 'payment', label: 'Payment ingest' },
        { id: 'nfraud', kind: 'fraud_check', label: 'Fraud screening' },
        { id: 'napprove', kind: 'approval', label: 'SCA / approval' },
        { id: 'nsettle', kind: 'settlement', label: 'Settlement rail' },
        { id: 'nretry', kind: 'retry', label: 'Retry buffer' },
        { id: E, kind: 'end', label: 'Exit' },
      ],
      edges: [
        { id: 'e0', source: S, target: 'npay' },
        { id: 'e1', source: 'npay', target: 'nfraud' },
        { id: 'e2', source: 'nfraud', target: 'napprove', label: 'clear' },
        { id: 'e3', source: 'napprove', target: 'nsettle' },
        { id: 'e4', source: 'nsettle', target: E },
        { id: 'e5', source: 'nfraud', target: 'nretry', label: 'soft decline' },
        { id: 'e6', source: 'nretry', target: 'nfraud', label: 're-present' },
      ],
      simulation: spine(
        [S, 'npay', 'nfraud', 'napprove', 'nsettle', E],
        900,
      ),
    },
  },
  {
    id: 'instant-refund',
    title: 'Instant refund',
    subtitle: 'Wallet fund → screening → route ok/challenge → ledger sync',
    flow: {
      id: 'instant-refund',
      name: 'Instant refund path',
      metadata: { domain: 'payments' },
      nodes: [
        { id: S, kind: 'start', label: 'Entry' },
        { id: 'nw', kind: 'wallet', label: 'Wallet ledger' },
        { id: 'npay', kind: 'payment', label: 'Refund post' },
        { id: 'nfraud', kind: 'fraud_check', label: 'Refund screening' },
        { id: 'nroute', kind: 'routing', label: 'Route policy' },
        { id: 'napprove', kind: 'approval', label: 'Manual OK' },
        { id: 'nrec', kind: 'reconciliation', label: 'Ledger sync' },
        { id: E, kind: 'end', label: 'Exit' },
      ],
      edges: [
        { id: 'e0', source: S, target: 'nw' },
        { id: 'e1', source: 'nw', target: 'npay' },
        { id: 'e2', source: 'npay', target: 'nfraud' },
        { id: 'e3', source: 'nfraud', target: 'nroute' },
        { id: 'e4', source: 'nroute', target: 'napprove', label: 'challenge' },
        { id: 'e5', source: 'nroute', target: 'nrec', label: 'auto' },
        { id: 'e6', source: 'napprove', target: 'nrec' },
        { id: 'e7', source: 'nrec', target: E },
      ],
      simulation: spine([S, 'nw', 'npay', 'nfraud', 'nroute', 'nrec', E], 850),
    },
  },
  {
    id: 'crypto-onramp',
    title: 'Crypto on-ramp',
    subtitle: 'Wallet → route chain → fraud → settlement rail',
    flow: {
      id: 'crypto-onramp',
      name: 'Crypto on-ramp',
      metadata: { domain: 'crypto' },
      nodes: [
        { id: S, kind: 'start', label: 'Entry' },
        { id: 'nw', kind: 'wallet', label: 'Custodial wallet' },
        { id: 'nroute', kind: 'routing', label: 'Chain / rail pick' },
        { id: 'nfraud', kind: 'fraud_check', label: 'AML screening' },
        { id: 'nsettle', kind: 'settlement', label: 'On-chain settle' },
        { id: 'nretry', kind: 'retry', label: 'Resubmit' },
        { id: E, kind: 'end', label: 'Exit' },
      ],
      edges: [
        { id: 'e0', source: S, target: 'nw' },
        { id: 'e1', source: 'nw', target: 'nroute' },
        { id: 'e2', source: 'nroute', target: 'nfraud' },
        { id: 'e3', source: 'nfraud', target: 'nsettle', label: 'pass' },
        { id: 'e4', source: 'nfraud', target: 'nretry', label: 'review' },
        { id: 'e5', source: 'nretry', target: 'nroute', label: 're-quote' },
        { id: 'e6', source: 'nsettle', target: E },
      ],
      simulation: spine([S, 'nw', 'nroute', 'nfraud', 'nsettle', E], 880),
    },
  },
  {
    id: 'treasury-sweep',
    title: 'Treasury sweep',
    subtitle: 'Rec batch → route destinations → settlement → wallets',
    flow: {
      id: 'treasury-sweep',
      name: 'Treasury sweep',
      metadata: { domain: 'treasury' },
      nodes: [
        { id: S, kind: 'start', label: 'Entry' },
        { id: 'nrec', kind: 'reconciliation', label: 'Positions recon' },
        { id: 'nroute', kind: 'routing', label: 'Sweep router' },
        { id: 'nsettle', kind: 'settlement', label: 'CLS / ACH' },
        { id: 'nw', kind: 'wallet', label: 'House wallet' },
        { id: 'nretry', kind: 'retry', label: 'Retry queue' },
        { id: E, kind: 'end', label: 'Exit' },
      ],
      edges: [
        { id: 'e0', source: S, target: 'nrec' },
        { id: 'e1', source: 'nrec', target: 'nroute' },
        { id: 'e2', source: 'nroute', target: 'nsettle', label: 'primary' },
        { id: 'e3', source: 'nroute', target: 'nretry', label: 'defer' },
        { id: 'e4', source: 'nretry', target: 'nroute', label: 'flush' },
        { id: 'e5', source: 'nsettle', target: 'nw' },
        { id: 'e6', source: 'nw', target: E },
      ],
      simulation: spine([S, 'nrec', 'nroute', 'nsettle', 'nw', E], 920),
    },
  },
  {
    id: 'batch-payout',
    title: 'Batch payout',
    subtitle: 'Router splits payrails → parallel settle → single recon',
    flow: {
      id: 'batch-payout',
      name: 'Batch payout',
      metadata: { domain: 'payments' },
      nodes: [
        { id: S, kind: 'start', label: 'Entry' },
        { id: 'nroute', kind: 'routing', label: 'Batch router' },
        { id: 'npay_a', kind: 'payment', label: 'Rail A file' },
        { id: 'npay_b', kind: 'payment', label: 'Rail B file' },
        { id: 'nset_a', kind: 'settlement', label: 'Settle A' },
        { id: 'nset_b', kind: 'settlement', label: 'Settle B' },
        { id: 'nrec', kind: 'reconciliation', label: 'Unified recon' },
        { id: E, kind: 'end', label: 'Exit' },
      ],
      edges: [
        { id: 'e0', source: S, target: 'nroute' },
        { id: 'e1', source: 'nroute', target: 'npay_a', label: 'slice A' },
        { id: 'e2', source: 'nroute', target: 'npay_b', label: 'slice B' },
        { id: 'e3', source: 'npay_a', target: 'nset_a' },
        { id: 'e4', source: 'npay_b', target: 'nset_b' },
        { id: 'e5', source: 'nset_a', target: 'nrec' },
        { id: 'e6', source: 'nset_b', target: 'nrec' },
        { id: 'e7', source: 'nrec', target: E },
      ],
      simulation: spine(
        [S, 'nroute', 'npay_a', 'nset_a', 'nrec', E],
        900,
      ),
    },
  },
  {
    id: 'internal-transfer',
    title: 'Internal transfer',
    subtitle: 'Wallet → routing rules → destination wallet',
    flow: {
      id: 'internal-transfer',
      name: 'Internal transfer',
      metadata: { domain: 'payments' },
      nodes: [
        { id: S, kind: 'start', label: 'Entry' },
        { id: 'nw1', kind: 'wallet', label: 'Source wallet' },
        { id: 'nroute', kind: 'routing', label: 'Limits / FX' },
        { id: 'nfraud', kind: 'fraud_check', label: 'Velocity check' },
        { id: 'nw2', kind: 'wallet', label: 'Dest wallet' },
        { id: E, kind: 'end', label: 'Exit' },
      ],
      edges: [
        { id: 'e0', source: S, target: 'nw1' },
        { id: 'e1', source: 'nw1', target: 'nroute' },
        { id: 'e2', source: 'nroute', target: 'nfraud' },
        { id: 'e3', source: 'nfraud', target: 'nw2', label: 'ok' },
        { id: 'e4', source: 'nw2', target: E },
      ],
      simulation: spine([S, 'nw1', 'nroute', 'nfraud', 'nw2', E], 800),
    },
  },
  {
    id: 'merchant-acquiring',
    title: 'Merchant acquiring',
    subtitle: 'Linear capture → settle → recon (clean spine)',
    flow: {
      id: 'merchant-acquiring',
      name: 'Merchant acquiring',
      metadata: { domain: 'payments' },
      nodes: [
        { id: S, kind: 'start', label: 'Entry' },
        { id: 'npay', kind: 'payment', label: 'POS capture' },
        { id: 'nsettle', kind: 'settlement', label: 'Acquirer settle' },
        { id: 'nrec', kind: 'reconciliation', label: 'Batch recon' },
        { id: E, kind: 'end', label: 'Exit' },
      ],
      edges: [
        { id: 'e0', source: S, target: 'npay' },
        { id: 'e1', source: 'npay', target: 'nsettle' },
        { id: 'e2', source: 'nsettle', target: 'nrec' },
        { id: 'e3', source: 'nrec', target: E },
      ],
      simulation: spine([S, 'npay', 'nsettle', 'nrec', E], 750),
    },
  },
  {
    id: 'subscription-renewal',
    title: 'Subscription renewal',
    subtitle: 'Recurring charge with fraud + approval gate',
    flow: {
      id: 'subscription-renewal',
      name: 'Subscription renewal',
      metadata: { domain: 'payments' },
      nodes: [
        { id: S, kind: 'start', label: 'Entry' },
        { id: 'npay', kind: 'payment', label: 'Renewal charge' },
        { id: 'nfraud', kind: 'fraud_check', label: 'Risk screen' },
        { id: 'napprove', kind: 'approval', label: 'SCA step-up' },
        { id: 'nsettle', kind: 'settlement', label: 'Billing settle' },
        { id: 'nw', kind: 'wallet', label: 'Credits wallet' },
        { id: E, kind: 'end', label: 'Exit' },
      ],
      edges: [
        { id: 'e0', source: S, target: 'npay' },
        { id: 'e1', source: 'npay', target: 'nfraud' },
        { id: 'e2', source: 'nfraud', target: 'napprove' },
        { id: 'e3', source: 'napprove', target: 'nsettle' },
        { id: 'e4', source: 'nsettle', target: 'nw' },
        { id: 'e5', source: 'nw', target: E },
      ],
      simulation: spine([S, 'npay', 'nfraud', 'napprove', 'nsettle', 'nw', E], 860),
    },
  },
  {
    id: 'cross-border-fx',
    title: 'Cross-border FX',
    subtitle: 'Route corridor → fraud → dual approval → settle',
    flow: {
      id: 'cross-border-fx',
      name: 'Cross-border FX',
      metadata: { domain: 'payments' },
      nodes: [
        { id: S, kind: 'start', label: 'Entry' },
        { id: 'nroute', kind: 'routing', label: 'Corridor pick' },
        { id: 'nfraud', kind: 'fraud_check', label: 'Compliance' },
        { id: 'napprove', kind: 'approval', label: 'Treasury sign-off' },
        { id: 'nsettle', kind: 'settlement', label: 'SWIFT / RTP' },
        { id: 'nretry', kind: 'retry', label: 'Repair queue' },
        { id: E, kind: 'end', label: 'Exit' },
      ],
      edges: [
        { id: 'e0', source: S, target: 'nroute' },
        { id: 'e1', source: 'nroute', target: 'nfraud' },
        { id: 'e2', source: 'nfraud', target: 'napprove', label: 'release' },
        { id: 'e3', source: 'nfraud', target: 'nretry', label: 'hold' },
        { id: 'e4', source: 'nretry', target: 'nroute', label: 're-route' },
        { id: 'e5', source: 'napprove', target: 'nsettle' },
        { id: 'e6', source: 'nsettle', target: E },
      ],
      simulation: spine([S, 'nroute', 'nfraud', 'napprove', 'nsettle', E], 900),
    },
  },
  {
    id: 'chargeback',
    title: 'Chargeback dispute',
    subtitle: 'Ledger hook → fraud narrative → approval → settlement credit',
    flow: {
      id: 'chargeback',
      name: 'Chargeback dispute',
      metadata: { domain: 'risk' },
      nodes: [
        { id: S, kind: 'start', label: 'Entry' },
        { id: 'nrec', kind: 'reconciliation', label: 'CB intake' },
        { id: 'nfraud', kind: 'fraud_check', label: 'Evidence fit' },
        { id: 'napprove', kind: 'approval', label: 'Dispute desk' },
        { id: 'nsettle', kind: 'settlement', label: 'Chargeback settle' },
        { id: 'nretry', kind: 'retry', label: 'Evidence retry' },
        { id: E, kind: 'end', label: 'Exit' },
      ],
      edges: [
        { id: 'e0', source: S, target: 'nrec' },
        { id: 'e1', source: 'nrec', target: 'nfraud' },
        { id: 'e2', source: 'nfraud', target: 'napprove', label: 'accept' },
        { id: 'e3', source: 'nfraud', target: 'nretry', label: 'needs docs' },
        { id: 'e4', source: 'nretry', target: 'nfraud', label: 're-review' },
        { id: 'e5', source: 'napprove', target: 'nsettle' },
        { id: 'e6', source: 'nsettle', target: E },
      ],
      simulation: spine([S, 'nrec', 'nfraud', 'napprove', 'nsettle', E], 910),
    },
  },
  {
    id: 'liquidity-park',
    title: 'Liquidity park',
    subtitle: 'Idle cash wallet → recon snapshot → route → market settle',
    flow: {
      id: 'liquidity-park',
      name: 'Liquidity park',
      metadata: { domain: 'treasury' },
      nodes: [
        { id: S, kind: 'start', label: 'Entry' },
        { id: 'nw', kind: 'wallet', label: 'Park wallet' },
        { id: 'nrec', kind: 'reconciliation', label: 'NAV snapshot' },
        { id: 'nroute', kind: 'routing', label: 'Venue router' },
        { id: 'nsettle', kind: 'settlement', label: 'MMF settle' },
        { id: E, kind: 'end', label: 'Exit' },
      ],
      edges: [
        { id: 'e0', source: S, target: 'nw' },
        { id: 'e1', source: 'nw', target: 'nrec' },
        { id: 'e2', source: 'nrec', target: 'nroute' },
        { id: 'e3', source: 'nroute', target: 'nsettle', label: 'allocate' },
        { id: 'e4', source: 'nsettle', target: E },
      ],
      simulation: spine([S, 'nw', 'nrec', 'nroute', 'nsettle', E], 870),
    },
  },
  {
    id: 'rtp-instant',
    title: 'RTP instant',
    subtitle: 'Wallet liquidity → route RTP/FedNow → settle → recon proof',
    flow: {
      id: 'rtp-instant',
      name: 'RTP instant credit',
      metadata: { domain: 'payments' },
      nodes: [
        { id: S, kind: 'start', label: 'Entry' },
        { id: 'nw', kind: 'wallet', label: 'Prefunded wallet' },
        { id: 'nroute', kind: 'routing', label: 'RTP vs ACH' },
        { id: 'npay', kind: 'payment', label: 'Push construct' },
        { id: 'nsettle', kind: 'settlement', label: 'Instant settle' },
        { id: 'nrec', kind: 'reconciliation', label: 'Proof snapshot' },
        { id: E, kind: 'end', label: 'Exit' },
      ],
      edges: [
        { id: 'e0', source: S, target: 'nw' },
        { id: 'e1', source: 'nw', target: 'nroute' },
        { id: 'e2', source: 'nroute', target: 'npay', label: 'instant' },
        { id: 'e3', source: 'npay', target: 'nsettle' },
        { id: 'e4', source: 'nsettle', target: 'nrec' },
        { id: 'e5', source: 'nrec', target: E },
      ],
      simulation: spine([S, 'nw', 'nroute', 'npay', 'nsettle', 'nrec', E], 840),
    },
  },
  {
    id: 'fraud-escalation',
    title: 'Fraud escalation',
    subtitle: 'Payment stuck → fraud loops → manual approval outlet',
    flow: {
      id: 'fraud-escalation',
      name: 'Fraud escalation',
      metadata: { domain: 'risk' },
      nodes: [
        { id: S, kind: 'start', label: 'Entry' },
        { id: 'npay', kind: 'payment', label: 'Suspicious txn' },
        { id: 'nfraud', kind: 'fraud_check', label: 'Rules engine' },
        { id: 'nroute', kind: 'routing', label: 'Escalation tier' },
        { id: 'napprove', kind: 'approval', label: 'SOC analyst' },
        { id: 'nsettle', kind: 'settlement', label: 'Safe release' },
        { id: 'nretry', kind: 'retry', label: 'Cool-off queue' },
        { id: E, kind: 'end', label: 'Exit' },
      ],
      edges: [
        { id: 'e0', source: S, target: 'npay' },
        { id: 'e1', source: 'npay', target: 'nfraud' },
        { id: 'e2', source: 'nfraud', target: 'nroute', label: 'score' },
        { id: 'e3', source: 'nroute', target: 'napprove', label: 'tier-2' },
        { id: 'e4', source: 'nroute', target: 'nretry', label: 'defer' },
        { id: 'e5', source: 'nretry', target: 'nfraud', label: 'replay' },
        { id: 'e6', source: 'napprove', target: 'nsettle' },
        { id: 'e7', source: 'nsettle', target: E },
      ],
      simulation: spine(
        [S, 'npay', 'nfraud', 'nroute', 'napprove', 'nsettle', E],
        890,
      ),
    },
  },
]

export const DEFAULT_SCENARIO_ID = SCENARIOS[0]!.id

/** @deprecated Use scenarios from SCENARIOS — kept for imports */
export const sampleFlow = SCENARIOS[0]!.flow
